### ISSUE TITLE
Display notifications in the UI

### ISSUE THREAD

**Issue by crykn** [eskalon/ProjektGG#24]
### Deatils
Notifications should be displayed in the UI of `GameMapScreen`.

### Tasks
- [ ] The notifications (currently saved in `GameClient#getNotifications()`) should be displayed as banners (new `ImageButtons` with the drawables `notification` & `notification_selected`) in `GameMapScreen`; on top of the banners, [icons](https://opengameart.org/content/700-rpg-icons) could be displayed to indicated the type of the notification
- [ ] A click on those notifications should open a dialog (style: `window`), which displays the text of the notification 
- [ ] In additon, the `GameMapScreen` should subscribe to the `NewNotificationEvent` and add new notifications to the UI (the list in `GameClient#getNotifications()` should have already been updated when the event is dispatched)
- [ ] Users should be able to dismiss notifications via a right click (if they don't require any interactions) and by opening and dealing with them.
