### ISSUE TITLE
Fill the UI of the map screen with life

### ISSUE THREAD

**Issue by crykn** [eskalon/ProjektGG#26]
﻿**Fill the UI of the map screen with life.**

### Details
The UI of the map screen should use real data and not just placeholders. 

### Tasks
- [ ] When initialising the In der `GameMapScreen` properly set the icon, the name, the gold, the year and the time.
- [ ] Add a subscriber for the `ReloadUIEvent` (?) that resets the UI values (icon, name und gold)
- [ ] Regularly update the time value; maybe do so without relying on the `ReloadUIEvent`, but rather by changing the value every frame in the render method
