### ISSUE TITLE
Add a singleplayer feature

### ISSUE THREAD

**Issue by crykn** [eskalon/ProjektGG#29]
﻿**Add a single player feature.**

### Details
A "Singleplayer" button should be added to the main menu that starts a local game after showing a config screen.

### Tasks
- [ ] Add a `SingeplayerCreationScreen` and link it in the main menu 
- [ ] In this screen, start a single player game, i.e. start a server, automatically connect the client and then set the client to be ready.
- [ ] For debugging purposes, implement a command line arg that allows skipping the main menu screen and starting right into a single player game
