### ISSUE TITLE
Implement elections for open positions

### ISSUE THREAD

**Issue by crykn** [eskalon/ProjektGG#30]
### Details
Most of the technical stuff needed for voting is already implemented, since impeachment votes already work. So this issue is mainly about adding the necessary UI as well as thoroughly testing the feature.

### Tasks
In the `GameInHouseScreen` for the _Townhall_ there is already a button, to apply for a position (`applyForPositionButton`).
- [ ] After clicking this button, a list with all available position fot the character should be displayed (check city.getPositions().entrySet() for that)
- [ ] After clicking an open position, it should be shown (1.) who already applied and (2.) who is part of the council that is responsible for filling the position
- [ ] The there is an "Apply" button, which takes into account the maximum number of possible applications; this button relays an "applied for an office" command to the server; this command is then distributed to the different simulations; check the impeachment proceedings to see how this works
- [ ] The votings themselves are held at the beginning of a new round via a special voting screen 

### Future ideas
Later on, voting on legislation can be implemented.
